### ISSUE TITLE
Beacon no longer needs to be lit in 1.18

### ISSUE THREAD

**Issue by DarkYuan** [Ephys/minecraft-magic-feather#18] opened 2022-07-19 18:26 UTC
While there are config options to change the base radius and step radius, there's no way to make it required to be lit but still have even steps up for range. Vanilla beacon range behavior is [0, 20, 30, 40, 50], but with the config it's only possible to have [10, 20, 30, 40, 50] or [0, 10, 20, 30, 40].

Proposed fix: "base_range" should pertain to a lit beacon, rather than a beacon on the ground with nothing under it, in which case the default config would be 20.

**Comment by ephys** [comment] 2022-07-19 20:26
After doing a series of tests I can confirm that there is a bug:

- no base: 10 range ❌
- block above base: 0 range ✅
- 1 level: 20 range ✅
- 2 levels: 30 range ✅

I think that bug has been there ever since the first implementation for MC 1.10 as I never rewrote the range logic

Just pushed a fix: https://github.com/ephys/minecraft-magic-feather/commit/11eeb115633e6ae4af506cfae8cad3249ac91f58, I'll close once it's released :)

**Comment by ephys** [comment] 2022-07-19 21:06
Here we go https://www.curseforge.com/minecraft/mc-mods/magic-feather/files/3885425 (edit: once curseforge has approved it)

**Closed as completed by ephys** 2022-07-19 21:06 UTC
